config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations]
  root to: "home#index"
  get "/user_management", to: "user_management#index"
  get "/new_admin", to: "user_management#new_admin"
  get "/new_domain", to: "user_management#new_domain"
  post "/create_domain", to: "user_management#create_domain"
  post "/load_products", to: "user_management#load_products"
  post "/create_admin", to: "user_management#create_admin"
  namespace :api do
    namespace :v1 do
      resources :checkout do
        collection do
          post :import_checkout_success
        end
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/controllers/user_management_controller.rb
class UserManagementController < ApplicationController
  before_action :authenticate_user!
  before_action :check_role

  def index
  end

  def new_admin
  end

  def create_admin
    User.create! email: params["user"]["email"], password: params["user"]["password"], domain: params["selected_domains"], role: :admin

    redirect_to user_management_path
  end

  def new_domain
  end

  def create_domain
    Domain.create! domain_name: params[:domain]["domain_name"]

    redirect_to root_path
  end

  def load_products
    response = HTTParty.get('https://smapmart.com/wp-json/api-product/v1/get-product')

    if response.success?
      response.parsed_response["products"].each do |data|
        Product.create transform_keys(data).except("url_product")
      end
    else
      puts "HTTP Request failed"
      nil
    end
  end

  private

  def check_role
    if current_user.admin?
      redirect_to root_path
    end
  end

  def transform_keys(data)
    data['product_id'] = data.delete('id')
    data
  end
end

app/views/user_management/new_admin.html.erb
    <div data-layout-mode="light"  data-sidebar-size="default" data-theme-layout="vertical" class="bg-[#EEF0FC] dark:bg-gray-900">
        <div class="ltr:flex flex-1 rtl:flex-row-reverse">
            <div class="page-wrapper relative ltr:ml-auto rtl:mr-auto rtl:ml-0 w-[calc(100%-260px)] px-4 pt-[64px] duration-300" style="margin: 0 auto !important;">
                <div class="xl:w-full">
                    <div class="flex flex-wrap">
                        <div class="flex items-center py-4 w-full">
                            <div class="w-full">
                                <div class="flex flex-wrap justify-between">
                                    <div class="items-center ">
                                        <h1 class="font-medium text-3xl block dark:text-slate-100">Create Admin</h1>
                                    </div><!--end /div-->
                                </div><!--end /div-->
                            </div><!--end /div-->
                        </div><!--end /div-->
                    </div><!--end /div-->
                </div><!--end container-->

                <div class="xl:w-full  min-h-[calc(100vh-152px)] relative pb-14">
                    <div class="grid md:grid-cols-12 lg:grid-cols-12 xl:grid-cols-12 gap-4 mb-4">

                        <div class="sm:col-span-12  md:col-span-12 lg:col-span-8 xl:col-span-12 xl:col-start-4 ">
                            <div class="bg-white dark:bg-gray-900 border border-slate-200 dark:border-slate-700/40  rounded-md w-full relative mb-4">
                                <div class="border-b border-slate-200 dark:border-slate-700/40 py-3 px-4 dark:text-slate-300/70">
                                    <div class="flex-none md:flex">
                                        <h4 class="font-medium text-lg flex-1 self-center mb-2 md:mb-0">Create new Admin</h4>
                                    </div>
                                </div><!--end header-title-->
                                <div class="flex-auto p-4 ">
                                  <%= form_for(User.new, url: create_admin_path) do |form| %>
                                    <div class="mb-2">
                                      <label for="email" class="font-medium text-sm text-slate-600 dark:text-slate-400">Email</label>
                                      <%= form.email_field :email, autofocus: true, autocomplete: "email", class: "form-input w-full rounded-md mt-1 border border-slate-300/60 dark:border-slate-700 dark:text-slate-300 bg-transparent px-3 py-1 focus:outline-none focus:ring-0 placeholder:text-slate-400/70 placeholder:font-normal placeholder:text-sm hover:border-slate-400 focus:border-primary-500 dark:focus:border-primary-500  dark:hover:border-slate-700", placeholder: "name@gmail.com", required: true %>
                                    </div>
                                    <div class="mb-2">
                                      <label for="password" class="font-medium text-sm text-slate-600 dark:text-slate-400">Password</label>
                                      <%= form.password_field :password, autocomplete: "new-password", class: "form-input w-full rounded-md mt-1 border border-slate-300/60 dark:border-slate-700 dark:text-slate-300 bg-transparent px-3 py-1 focus:outline-none focus:ring-0 placeholder:text-slate-400/70 placeholder:font-normal placeholder:text-sm hover:border-slate-400 focus:border-primary-500 dark:focus:border-primary-500  dark:hover:border-slate-700", required: true%>
                                    </div>
                                    <div class="mb-2">
                                      <label for="domain" class="font-medium text-sm text-slate-600 dark:text-slate-400">Domain</label>
                                      <select id="selectedDomains" multiple placeholder="Choose skills" data-allow-clear="1" class="abc form-input w-full rounded-md mt-1 border border-slate-300/60 dark:border-slate-700 dark:text-slate-300 bg-transparent px-3 py-1 focus:outline-none focus:ring-0 placeholder:text-slate-400/70 placeholder:font-normal placeholder:text-sm hover:border-slate-400 focus:border-primary-500 dark:focus:border-primary-500  dark:hover:border-slate-700">
                                        <% Domain.all.pluck(:domain_name).uniq.each do |domain_name| %>
                                          <option><%= domain_name %></option>
                                        <% end %>
                                      </select>
                                    </div>
                                    <button type="submit" class="inline-block focus:outline-none text-primary-500 hover:bg-primary-500 hover:text-white bg-transparent border border-gray-200 dark:bg-transparent dark:text-primary-500 dark:hover:text-white dark:border-gray-700 dark:hover:bg-primary-500  text-sm font-medium py-1 px-3 rounded mb-1">Submit</button>
                                    <button type="text" class="inline-block focus:outline-none text-red-500 hover:bg-red-500 hover:text-white bg-transparent border border-gray-200 dark:bg-transparent dark:text-red-500 dark:hover:text-white dark:border-gray-700 dark:hover:bg-red-500  text-sm font-medium py-1 px-3 rounded mb-1">Cancel</button>
                                  <% end %>
                                </div><!--end card-body-->
                            </div> <!--end card-->
                        </div><!--end col-->
                    </div><!--end inner-grid-->
                    <!-- footer -->
                    <div class="absolute bottom-0 -left-4 -right-4 block print:hidden border-t p-4 h-[52px] dark:border-slate-700/40">
                        <div class="container">
                          <!-- Footer Start -->
                          <footer
                            class="footer bg-transparent  text-center  font-medium text-slate-600 dark:text-slate-400 md:text-left "
                          >
                            &copy;
                            GOLDIGI
                          </footer>
                          <!-- end Footer -->
                        </div>
                      </div>
                </div><!--end container-->
            </div><!--end page-wrapper-->
        </div><!--end /div-->


        <!-- JAVASCRIPTS -->
        <!-- <div class="menu-overlay"></div> -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js" integrity="sha512-2ImtlRlf2VVmiGZsjm9bEyhjGW4dU7B6TNwh/hx/iSByxNENtj3WVE6o/9Lj4TJeVXPi4bnOIMXFIJJAeufa0A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script>
          $('.abc').select2();

          $('.abc').on('select2:opening select2:closing', function( event ) {
              var $searchfield = $(this).parent().find('.select2-search__field');
              $searchfield.prop('disabled', true);
          });
        </script>

        <script>
          document.addEventListener('DOMContentLoaded', function() {
            const form = document.querySelector('form');
            const selectedDomainsInput = document.createElement('input');
            selectedDomainsInput.type = 'hidden';
            selectedDomainsInput.name = 'selected_domains'; // Change to the appropriate attribute name
            form.appendChild(selectedDomainsInput);

            $('#selectedDomains').select2(); // Initialize Select2

            form.addEventListener('submit', function() {
              const selectedDomains = $('#selectedDomains').val();
              selectedDomainsInput.value = selectedDomains.join(',');
            });
          });
        </script>
        <%# <script src="assets/libs/lucide/umd/lucide.min.js"></script>
        <script src="assets/libs/simplebar/simplebar.min.js"></script>
        <script src="assets/libs/flatpickr/flatpickr.min.js"></script>
        <script src="assets/libs/@frostui/tailwindcss/frostui.js"></script>

        <script src="assets/libs/prismjs/prism.js"></script>
        <script src="assets/js/app.js"></script> %>
        <!-- JAVASCRIPTS -->
    </div>

app/views/user_management/new_domain.html.erb
    <div data-layout-mode="light"  data-sidebar-size="default" data-theme-layout="vertical" class="bg-[#EEF0FC] dark:bg-gray-900">
        <div class="ltr:flex flex-1 rtl:flex-row-reverse">
            <div class="page-wrapper relative ltr:ml-auto rtl:mr-auto rtl:ml-0 w-[calc(100%-260px)] px-4 pt-[64px] duration-300" style="margin: 0 auto !important;">
                <div class="xl:w-full">
                    <div class="flex flex-wrap">
                        <div class="flex items-center py-4 w-full">
                            <div class="w-full">
                                <div class="flex flex-wrap justify-between">
                                    <div class="items-center ">
                                        <h1 class="font-medium text-3xl block dark:text-slate-100">Create Domain</h1>
                                    </div><!--end /div-->
                                </div><!--end /div-->
                            </div><!--end /div-->
                        </div><!--end /div-->
                    </div><!--end /div-->
                </div><!--end container-->

                <div class="xl:w-full  min-h-[calc(100vh-152px)] relative pb-14">
                    <div class="grid md:grid-cols-12 lg:grid-cols-12 xl:grid-cols-12 gap-4 mb-4">

                        <div class="sm:col-span-12  md:col-span-12 lg:col-span-8 xl:col-span-6 xl:col-start-4 ">
                            <div class="bg-white dark:bg-gray-900 border border-slate-200 dark:border-slate-700/40  rounded-md w-full relative mb-4">
                                <div class="border-b border-slate-200 dark:border-slate-700/40 py-3 px-4 dark:text-slate-300/70">
                                    <div class="flex-none md:flex">
                                        <h4 class="font-medium text-lg flex-1 self-center mb-2 md:mb-0">Create new Domain</h4>
                                    </div>
                                </div>
                                <div class="flex-auto p-4 ">
                                  <%= form_for(Domain.new, url: create_domain_path) do |form| %>
                                    <div class="mb-2">
                                      <label for="email" class="font-medium text-sm text-slate-600 dark:text-slate-400">Email</label>
                                      <%= form.text_field :domain_name, autofocus: true, class: "form-input w-full rounded-md mt-1 border border-slate-300/60 dark:border-slate-700 dark:text-slate-300 bg-transparent px-3 py-1 focus:outline-none focus:ring-0 placeholder:text-slate-400/70 placeholder:font-normal placeholder:text-sm hover:border-slate-400 focus:border-primary-500 dark:focus:border-primary-500  dark:hover:border-slate-700", placeholder: "Nhập tên domain", required: true %>
                                    </div>
                                    <button type="submit" class="inline-block focus:outline-none text-primary-500 hover:bg-primary-500 hover:text-white bg-transparent border border-gray-200 dark:bg-transparent dark:text-primary-500 dark:hover:text-white dark:border-gray-700 dark:hover:bg-primary-500  text-sm font-medium py-1 px-3 rounded mb-1">Submit</button>
                                    <button type="text" class="inline-block focus:outline-none text-red-500 hover:bg-red-500 hover:text-white bg-transparent border border-gray-200 dark:bg-transparent dark:text-red-500 dark:hover:text-white dark:border-gray-700 dark:hover:bg-red-500  text-sm font-medium py-1 px-3 rounded mb-1">Cancel</button>
                                  <% end %>
                                </div>
                            </div>
                        </div><!--end col-->
                    </div><!--end inner-grid-->
                    <!-- footer -->
                    <div class="absolute bottom-0 -left-4 -right-4 block print:hidden border-t p-4 h-[52px] dark:border-slate-700/40">
                        <div class="container">
                          <!-- Footer Start -->
                          <footer
                            class="footer bg-transparent  text-center  font-medium text-slate-600 dark:text-slate-400 md:text-left "
                          >
                            &copy;
                            GOLDIGI
                          </footer>
                          <!-- end Footer -->
                        </div>
                      </div>
                </div><!--end container-->
            </div><!--end page-wrapper-->
        </div><!--end /div-->

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js" integrity="sha512-2ImtlRlf2VVmiGZsjm9bEyhjGW4dU7B6TNwh/hx/iSByxNENtj3WVE6o/9Lj4TJeVXPi4bnOIMXFIJJAeufa0A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    </div>